### ISSUE TITLE
Implicit conversion to ValueTuple

### ISSUE THREAD

**Issue by louthy** [richbryant/BetterUnit#1]
Not sure if you've [seen this in the language-ext implementation](https://github.com/louthy/language-ext/blob/main/LanguageExt.Core/DataTypes/Unit/Unit.cs), but I think this would have future value (if the Roslyn team ever make the empty tuple `()` valid).

```c#
    public static implicit operator ValueTuple(Unit _) => 
        default;
        
    public static implicit operator Unit(ValueTuple _) => 
        default;
```

**Comment by richbryant** [comment]
It should certainly be included.  The idea of this implementation was to cover all three of the major libraries so apart from anything else, I can't leave it out or it'd make a breaking change.

And yes, we can hope for eventual BCL support there.

**Comment by richbryant** [comment]
That's done, I'll close this one now.
